WITH RECURSIVE GEN AS(
    -- 1세대
    SELECT ID, 1 AS GENERATION 
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, GENERATION + 1
    FROM ECOLI_DATA E
    JOIN GEN G ON E.PARENT_ID = G.ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
-- 부모 개체가 있는 대장균의 부모 개체 == 자식이 있는 개체
-- 가 아닌 대장균
WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY GENERATION;