-- 코드를 입력하세요
SELECT DISTINCT COM.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR COM
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON COM.CAR_ID = HIS.CAR_ID
WHERE CAR_TYPE = '세단' AND MONTH(START_DATE) = 10
ORDER BY COM.CAR_ID DESC;